DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE categories (
  id SERIAL PRIMARY KEY NOT NULL,
  category_name VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  logo_url VARCHAR(255),
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE accounts (
  id SERIAL PRIMARY KEY NOT NULL,
  account_name VARCHAR(255) NOT NULL,
  balance INTEGER NOT NULL DEFAULT 0,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  note TEXT
);

CREATE TABLE transactions (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  account_id INTEGER REFERENCES accounts(id) ON DELETE CASCADE,
  account_id_to INTEGER REFERENCES accounts(id) ON DELETE CASCADE DEFAULT NULL,
  amount INTEGER NOT NULL DEFAULT 0,
  transaction_date DATE NOT NULL,
  notes TEXT
);